AllCops:
    NewCops: enable

Layout/LineLength:
    Enabled: false

Metrics/ClassLength:
    Max: 200

Metrics/MethodLength:
    Max: 20

Style/CombinableLoops:
    Enabled: false

Style/IfUnlessModifier:
    Enabled: false
